logging:
    level:
        com:
            example:
                fundserviceapi:
                    client: DEBUG
            woniuxy:
                purchase: DEBUG
        root: INFO
    pattern:
        console: ${CONSOLE_LOG_PATTERN:%clr(${LOG_LEVEL_PATTERN:%5p}) %clr(|){faint}
            %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}
server:
    port: 8080
spring:
    jackson:
        serialization:
            FAIL_ON_EMPTY_BEANS: false
    application:
        name: purchase-service
    cloud:
        nacos:
            discovery:
                namespace: public
                password: nacos
                server-addr: 192.172.0.201:8848
                username: nacos
#                group: LeTian
    shardingsphere:
        datasource:
            names: ds0, ds1
            ds0:
                driver-class-name: com.mysql.cj.jdbc.Driver
                jdbc-url: jdbc:mysql://192.172.0.201:3307/erp?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
                password: 123456
                type: com.zaxxer.hikari.HikariDataSource
                username: root
            ds1:
                driver-class-name: com.mysql.cj.jdbc.Driver
                jdbc-url: jdbc:mysql://192.172.0.201:3308/erp?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
                password: 123456
                type: com.zaxxer.hikari.HikariDataSource
                username: root
        masterslave:
            load-balance-algorithm-type: round_robin
            master-data-source-name: ds0
            name: ms
            slave-data-source-names: ds1
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
                hbm2ddl:
                    auto: update
        show-sql: true
    rabbitmq:
        publisher-confirm-type: CORRELATED #确认消息到达交换机
        host: 192.172.0.201
        listener:
            direct:
                acknowledge-mode: manual
            simple:
                acknowledge-mode: manual
        password: guest
        port: 5672
        username: guest
