spring:
     profiles:
         active: test
#    redis:
#        host: 192.172.0.201
     main:
         banner-mode: off
         allow-bean-definition-overriding: true

#    datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        name: defaultDataSource
#        password: 123456
#        url: jdbc:mysql://192.172.0.201:3307/erp?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#        username: root
#    jpa:
#        show-sql: true
#        properties:
#            hibernate:
#                dialect: org.hibernate.dialect.MySQL8Dialect
#                format_sql: true
#                hbm2ddl:
#                    auto: update

#logging:
#    pattern:
#        console: '%clr(%5level) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
#    level:
#        com.woniu.outlet.client: DEBUG
#feign:
#    httpclient:
#        enabled: true # 激活 httpclient 的使用
#




#seata:
#    application-id: ${spring.application.name}
#    tx-service-group: my_test_tx_group
#    service:
#        vgroup-mapping:
#            my_test_tx_group: default
#    registry:
#        type: nacos
#        nacos:
#            server-addr: 192.172.0.201:8848
#            group: erp
#            application: seata-server
#            cluster: default
