server:
  port: 8080
spring:
  application:
    name: home-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.172.0.201:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: 123456
    url: jdbc:mysql://192.172.0.201:3307/erp?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true
        format_sql: true
        hbm2ddl:
          auto: update
    show-sql: true
  main:
    banner-mode: off
  rabbitmq:
    host: 192.172.0.201
    password: guest
    port: 5672
    username: guest
  redis:
    host: 192.172.0.201
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com:
      example: DEBUG
    root: INFO
  pattern:
    console: '%clr(%5level) %clr(|){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n'

